#!/bin/sh

if [ $# -lt 2 ];
    then echo "illegal number of parameters"
    exit
fi

if [ -f $1 ]; then
    STATUS=`sed 's/\r//' $1 2> /dev/null`
fi

# If empty, check timewarrior
if [ -z "$STATUS" ]; then
    STATUS=`timew | grep  "Tracking" | cut -d ' ' -f 2-`
fi

if [ -f $2 ]; then
    WOFFU=`sed 's/\r//' $2 2> /dev/null`
    if [ -n "$WOFFU" ]; then
        WOFFU="[$WOFFU]"
    fi
fi

echo $WOFFU $STATUS

