#!/bin/bash

controlc() {
    # Secure shutdown
    timew stop $1 $2
    echo "Bye!"
    exit
}

stopwatch(){
    date1=`date +%s`; 
    while true; do 
    days=$(( $(($(date +%s) - date1)) / 86400 ))
    echo -ne "$days day(s) and $(date -u --date @$((`date +%s` - $date1)) +%H:%M:%S)\r";
    sleep 10
    done
}


trap 'controlc' SIGINT
echo "Tracking $1 $2"

timew track "$1" $2
stopwatch
timew stop "$1" $2
